## 00. Pytorch Fundamentals (code-along session)

---



> Add blockquote



Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [43]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


## Introduction to tensors


### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [44]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [45]:
scalar.ndim

0

In [46]:
# Get tensor back as Python int
scalar.item()

7

In [47]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [48]:
vector.ndim

1

In [49]:
vector.shape

torch.Size([2])

In [50]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [51]:
MATRIX.ndim

2

In [52]:
MATRIX[1]

tensor([ 9, 10])

In [53]:
MATRIX.shape

torch.Size([2, 2])

In [54]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape

torch.Size([1, 3, 3])

In [57]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

 ### Random tensors

 Why random tensors?

 Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

 `Start with random numbers -> look at data -> update random numbers -> look at data -> update again.`

In [58]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0759, 0.8291, 0.5285, 0.3827],
        [0.1133, 0.0678, 0.2093, 0.8742],
        [0.0343, 0.6861, 0.6373, 0.4055]])

In [59]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (sometimes colour channels comes first)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [60]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [61]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [62]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [63]:
# Use torch.arange()
ones_to_ten = torch.arange(start=1, end=11, step=1)
ones_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=ones_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [65]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], # data
                               dtype = None, # what datatype is the tensor (e.g. float32 or float16)
                               device = "cpu", # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [66]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [68]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [69]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get shape from a tensor, can use `tensor.device`

In [70]:
# Create a tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8449, 0.1543, 0.8063, 0.8518],
        [0.4097, 0.9458, 0.5256, 0.9977],
        [0.6722, 0.8823, 0.0273, 0.0749]])

In [71]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}.")
print(f"Shape of tensor: {some_tensor.shape}.")
print(f"Device tensor is on: {some_tensor.device}.")

tensor([[0.8449, 0.1543, 0.8063, 0.8518],
        [0.4097, 0.9458, 0.5256, 0.9977],
        [0.6722, 0.8823, 0.0273, 0.0749]])
Datatype of tensor: torch.float32.
Shape of tensor: torch.Size([3, 4]).
Device tensor is on: cpu.


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [72]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [73]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [74]:
tensor

tensor([10, 20, 30])

In [75]:
# Subtract 10
tensor - 10

tensor([ 0, 10, 20])

In [76]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [77]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot products)

More information on multiplying matrices - https://www.mathisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satifsy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2) ` will work
* `(3, 2) @ (2, 3) ` will work

2. The result matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`


In [78]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [79]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [80]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [81]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 2.04 ms, sys: 0 ns, total: 2.04 ms
Wall time: 2.66 ms


In [82]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 836 µs, sys: 0 ns, total: 836 µs
Wall time: 794 µs


tensor(1400)

### One of the most common errors in deep learning: shape errors

In [83]:
# # Shapes for matrix multiplication
# tensor_A = torch.tensor([[1, 2],
#                          [3, 4],
#                          [5, 6]])
# tensor_B = torch.tensor([[7, 10],
#                          [8, 11],
#                          [9, 12]])
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

In [84]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.

A **transpose** swicthes the axes or dimensions of a given tensor.

In [85]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [86]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [87]:
# The matrix multiplication operations works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [88]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [89]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [90]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [91]:
# Find the mean - note: the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), torch.mean(x, dtype=torch.float32) # or

(tensor(45.), tensor(45.))

In [92]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [93]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [95]:
x[0]

tensor(0)

In [96]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [97]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined Shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [98]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [99]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [100]:
# Vhange the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [101]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [102]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [103]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [104]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [105]:
# torch.unsquueze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [106]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order (return a view)
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [107]:
x_original[0, 0, 0] = 728
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728.), tensor(728.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with numpy


In [108]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [109]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [110]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [111]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [112]:
# You can use the ":" to select "all" of the target dimensions
x[:, 0]

tensor([[1, 2, 3]])

In [113]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimensions
x[:, :, 1]

tensor([[2, 5, 8]])

In [114]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [115]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [116]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [117]:
# Index on x to return 9
x[-1, -1, -1]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`



In [118]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).to(torch.float32) # warning: when converting from numpy -> pytorch, pytorch reflects numpy;s default datatype of float64 unless specified optherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [119]:
# Change the value of array, what will this do to `tensor `?

array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [120]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [121]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Esentially what the random seed does is "flavour" the randomness.

In [122]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(torch.all(random_tensor_A == random_tensor_B))

tensor([[0.9072, 0.0643, 0.7868, 0.6108],
        [0.1458, 0.0649, 0.8953, 0.9666],
        [0.5456, 0.6445, 0.4902, 0.8924]])
tensor([[0.8547, 0.5302, 0.4923, 0.1642],
        [0.6161, 0.0538, 0.0144, 0.3933],
        [0.8455, 0.2511, 0.8934, 0.5898]])
tensor(False)


In [123]:
 # Let's make some random but reproducible tensors

 import torch

 # Set the random seed
 RANDOM_SEED = 42
 torch.manual_seed(RANDOM_SEED)
 random_tensor_C = torch.rand(3, 4)

 torch.manual_seed(RANDOM_SEED)
 random_tensor_D = torch.rand(3, 4)

 print(random_tensor_C)
 print(random_tensor_D)
 print(torch.all(random_tensor_C == random_tensor_D))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor(True)


Extra resources for reproducibility:
 * https://pytorch.org/docs/stable/notes/randomness.html
 * https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).config


### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU - there's lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

In [125]:
!nvidia-smi

Mon Feb 10 18:03:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   61C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [126]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [127]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [128]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [129]:
# Create a tensor (defaults on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [130]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) # "cuda"
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to the CPU


In [131]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [132]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.to("cpu")
tensor_back_on_cpu

tensor([1, 2, 3])

In [133]:
tensor_back_on_cpu.numpy()

array([1, 2, 3])

## Exercices & Extra-curriculum

### 1. Read the documentation:
* https://pytorch.org/docs/stable/tensors.html
* https://pytorch.org/docs/stable/cuda.html

### 2. Create a random tensor with shape (7, 7)

In [134]:
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

### 3. Perform a matrix multiplication on the tensor from 2 with another tensor of shape (1, 7) (hint: you may have to transpose the second tensor.)

In [135]:
another_random_tensor = torch.rand(1, 7)
another_random_tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]])

In [136]:
torch.matmul(random_tensor, another_random_tensor.T)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

### 4. Set the random seed to 0 and do exercises 2 & 3 over again.


In [138]:
torch.manual_seed(42)
random_tensor = torch.rand(7, 7)
torch.manual_seed(42)
another_random_tensor = torch.rand(1, 7)
torch.matmul(random_tensor, another_random_tensor.T)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
torch.manual_seed(1234) # ALSO SETS RANDOM SEED FOR CURRENT GPU

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [139]:
torch.manual_seed(1234)
T1 = torch.rand(2, 3).to("cuda")
torch.manual_seed(1234)
T2 = torch.rand(2, 3).to("cuda")

### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [143]:
result = torch.matmul(T1, T2.T)
result

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.


In [144]:
result.max(), result.min()

(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.


In [145]:
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [146]:
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = tensor.squeeze()
print(f"Original tensor: {tensor}, shape: {tensor.shape}")
print(f"Squeezed tensor: {squeezed_tensor}, shape: {squeezed_tensor.shape}")

Original tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), shape: torch.Size([1, 1, 1, 10])
Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), shape: torch.Size([10])
